apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 2
  selector:
    dc: US
  template:
    metadata:
      labels:
        dc: US
        team: t2
      name: p4
    spec:
      containers:
        - name: myweb
          image: httpd:latest
